In [2]:
# Checking NumPy version
import numpy as np

print(np.__version__)

1.24.2


In [3]:
# Creating NumPy Arrays
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
#  Array from list
num_list = [1, 2, 3, 4, 5]
num_array = np.array(num_list)
num_array

array([1, 2, 3, 4, 5])

In [6]:
# Let's use a tuple to create a NumPy array:
import numpy as np

num_tuple = (1, 2, 3, 4, 5)
arr = np.array(num_tuple)

print(arr)

[1 2 3 4 5]


## Dimensions in Arrays

In [8]:
# Create a 0-D array with value 21

import numpy as np

arr = np.array(21)

print(arr)

21


In [9]:
# Create a 1-D array containing the values 1,2,3,4,5:

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [10]:
# Create a 2-D array containing two arrays with the values 0,1,2 and 3,4,5,:

import numpy as np

arr = np.array([[0, 1, 2], [3, 4, 5,]])
print(arr)

[[0 1 2]
 [3 4 5]]


In [11]:
#Create a 3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3 and 4,5,6:

import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [12]:
# Check how many dimensions the arrays have:

import numpy as np

w = np.array(42)
x = np.array([1, 2, 3, 4, 5])
y = np.array([[1, 2, 3], [4, 5, 6]])
z = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(w.ndim)
print(x.ndim)
print(y.ndim)
print(z.ndim)

0
1
2
3


In [14]:
# Create an array with 5 dimensions and verify that it has 5 dimensions:

import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('Number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
Number of dimensions : 5


## Array Indexing

In [15]:
# Get the first element from the following array:

import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])

1


In [16]:
# Get the second element from the following array.

import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[1])

2


In [17]:
# Get third and fourth elements from the following array and multiply them.

import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[2] * arr[3])

12


## Accessing 2D Arrays

In [19]:
# Access the element on the first row, second column:

import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Second element on 1st row: ', arr[0, 1])

Second element on 1st row:  2


In [20]:
# Access the element on the 2nd row, 5th column:

import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Fifth element on 2nd row: ', arr[1, 4])

Fifth element on 2nd row:  10


## Access 3-D Arrays

In [21]:
# Access the third element of the second array of the first array:

import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


## Negative Indexing

In [22]:
# Use negative indexing to access an array from the end.

In [23]:
# Print the last element from the 2nd dim:

import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


## Slicing Arrays

In [24]:
# Slice elements from index 1 to index 5 from the following array:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [25]:
# Slice elements from index 4 to the end of the array:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

[5 6 7]


In [26]:
# Slice elements from the beginning to index 4 (not included):

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

[1 2 3 4]


## Negative Slicing

In [27]:
# Slice from the index 3 from the end to index 1 from the end:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


## Step

In [29]:
import numpy as np

# Return every other element from index 1 to index 5:

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [30]:
# Return every other element from the entire array:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


## Slicing 2-D Arrays

In [31]:
# From the second element, slice elements from index 1 to index 4 (not included):

import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4]) #Note: Remember that second element has index 1.

[7 8 9]


In [32]:
# From both elements, return index 2:

import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


In [33]:
#From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:

import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


## Checking Data Type of an Array

In [34]:
# Get the data type of an array object:

import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int32


In [35]:
# Get the data type of an array containing strings:

import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [36]:
#Create an array with data type string:

import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


## Converting Data Types of Exixting Arrays

In [37]:
#Change data type from float to integer by using 'i' as parameter value:

import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [38]:
# Change data type from float to integer by using int as parameter value:

import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [39]:
# Change data type from integer to boolean:

import numpy as np

arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


## Shape of an Array

In [ ]:
# NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.

In [41]:
#Print the shape of a 2-D array:

import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


## Sorting Arrays

In [43]:
#Sort the array:

import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

# Note: This method returns a copy of the array, leaving the original array unchanged.

[0 1 2 3]


In [44]:
# Sort the array alphabetically:

import numpy as np

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [45]:
#Sort a boolean array:

import numpy as np

arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


In [46]:
# Sort a 2-D array:

import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [47]:
# Floor division: the division result without the remainder
numpy_array_from_list = np.array([1, 2, 3, 4, 5])
print('original array: ', numpy_array_from_list)
ten_times_original = numpy_array_from_list // 10
print(ten_times_original)


original array:  [1 2 3 4 5]
[0 0 0 0 0]


## Normal Distribution

In [48]:
# Generate a random normal distribution of size 2x3:

from numpy import random

x = random.normal(size=(2, 3))

print(x)

[[ 0.51208624 -0.25725822 -1.0639147 ]
 [-0.38644158  1.03369566 -0.4005943 ]]


In [49]:
#Generate a random normal distribution of size 2x3 with mean at 1 and standard deviation of 2:

from numpy import random

x = random.normal(loc=1, scale=2, size=(2, 3))

print(x)

[[ 0.89907621  0.43532069 -1.47023183]
 [-1.11434071  1.93220253 -0.21280824]]


## Visualization of Normal Distribution

In [ ]:
from numpy import random
import matplotlib.pyplot as plt
import seaborn as sns

sns.distplot(random.normal(size=1000), hist=False)

plt.show()

In [ ]:
np_normal_dis = np.random.normal(5, 0.5, 100)
np_normal_dis
## min, max, mean, median, sd
print('min: ', two_dimension_array.min())
print('max: ', two_dimension_array.max())
print('mean: ',two_dimension_array.mean())
# print('median: ', two_dimension_array.median())
print('sd: ', two_dimension_array.std())